resourcestring                                     {deutsch}

  capForm1='Konfiguration für RC-Modelle mit SR24 bearbeiten';

  rsBind1='LED auf SR24 blinkt langsam:     Warten auf Verbindung.';
  rsBind2='LED auf SR24 leuchtet dauerhaft: Verbunden.';
  rsBind4='LED auf SR24 binkt schnell:      Bindemodus.';
  rsBind3='>>>>> Sende BIND Kommando...';
  rsHint='Hinweis: ';
  rsWarn='Warnung: ';
  rsErr= 'Fehler:  ';
  rsSave='Konfiguration speicher als...';
  rsDefault='# Standardeinstellungen';
  rsCheck='Prüfe die aktuelle Konfigurationsdatei im Texteditor.';

  errNoCon='SR24 nicht verbunden';
  errLoad='Lade Konfigurationsdatei zum Prüfen.';
  errInvPio='Ungültige GPIO pin Nummer.';
  rsValidNR='Gültige, aber nicht empfohlene GPIO pin Nummer.';
  rsWarnPWM='PWM Kanäle sollten nie Schaltern zugewiesen werden.';
  rsNoPins='Kein GPIO pins zugewiesen.';
  rsNoPWM='Kein PWM Kanal zugewiesen.';
  errPinX=' bereits benutzt. Soll dieser GPIO pin wirklich mehrfach benutzt werden?';
  errChanX=' bereits benutzt. Soll dieser PWM-Kanal wirklich mehrfach benutzt werden?';
  errInvChan='Ungültige RC-Kanal Nummer.';
  errPWMset='Ein PWM Kanal darf hier nicht zugewiesen werden.';
  rsCheckOK='Konfiguration sieht gut aus. Keine Inkonsistenzen gefunden.';
  rsDefaultSet='OK, das sind die Standardeinstellungen.';
  rsLines='Eine Konfigurationsdatei sollte eigentlich mehr als eine Zeile beinhalten. Diese hier wird nicht geprüft.';

  capClose='&Beenden';
  capOpen='Se&ttings';
  capDefault='Standard&einstellungen';
  capSave='&Speichern';
  capSaveAs='Speichern &als...';
  capBind='B&inden';
  capFindInfo='&Kurzinfo';
  capManual='Anleitung';
  capAbout='Über...';
  capHomepage='Homepage';
  capFile='&Datei';

  hntClose='Programm beenden. Alle nicht gespeicherten Änderungen gehen verloren.';
  hntOpen='Öffne die Konfigurationsdatei.';
  hntDefault='Lade die Standardeinstellungen - ein guter Startpunkt zum Anlegen einer neuen Konfigurationsdatei.';
  hntSaveAs='Konfigurationsdatei speichern als...';
  hntBind='Bindemodus für SR24 einstellen.';
  hntFindInfo='Lade einee Infodatei, wenn diese noch nicht geladen ist.';
  hntManual='Anleitung anzeigen.';
  hntAbout='About box.';
  hntHomepage='Homepage aufrufen. Auf der Seite "Kopter" gibt es eine Reihe interessanter Dokumentationen.';

