resourcestring                                     {english}

  capForm1='Edit settings for RC models with SR24';

  rsBind1='LED at SR24 slow binking: Waiting for connection.';
  rsBind2='LED at SR24 solid:        Connected to RC.';
  rsBind4='LED at SR24 fast binking: Bind mode.';
  rsBind3='>>>>> Sending BIND command...';
  rsHint='Hint:    ';
  rsWarn='Warning: ';
  rsErr= 'Error:   ';
  rsSave='Save settings file as';
  rsDefault='# Default settings';
  rsCheck='Checking current settings file in text editor.';

  errNoCon='SR24 not connected';
  errLoad='Load settings file to check.';
  errInvPio='Invalid GPIO pin number.';
  rsValidNR='Valid but not recommended GPIO pin.';
  rsWarnPWM='PWM channels should not assigned to switches.';
  rsNoPins='No GPIO pins assigned.';
  rsNoPWM='No PWM channels assigned.';
  errPinX=' already used. Do you really want to use this pin for multiple purposes?';
  errChanX=' already used. Do you really want to use this channel for multiple purposes?';
  errInvChan='Invalid RC channel number.';
  errPWMset='PWM channel must not assigned here.';
  rsCheckOK='Settings seems to be OK. No inconsistency found.';
  rsDefaultSet='OK, those are the default settings.';
  rsLines='A settings file should have more than one line. No check done.';

  capClose='&Close';
  capOpen='&Open settings';
  capDefault='&Load defaults';
  capSave='&Save';
  capSaveAs='Save &as...';
  capBind='&Bind RC';
  capFindInfo='Load &info';
  capManual='Manual';
  capAbout='About...';
  capHomepage='Homepage';
  capFile='&File';

  hntClose='Close application. All not saved changes are lost.';
  hntOpen='Open settings file.';
  hntDefault='Load default settings. A good start for creating a new settings file..';
  hntSaveAs='Save settings file as...';
  hntBind='Bind receiver to RC.';
  hntFindInfo='Load info file if not yet loaded.';
  hntManual='Open user manual.';
  hntAbout='About box.';
  hntHomepage='Open my homepage. There you can find also other useful information in "Kopter" section.';


